config/routes.rb
Rails.application.routes.draw do
    root :to =>'lists#index'

    resources :lists do
    resources :tasks, :except => [:show, :index]
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  validates :name, :presence => true

  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description,  :presence => true
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end

    def edit
      @list = List.find(params[:id])
    end

    def update
      @list = List.find(params[:id])
      if @list.update(list_params)
        flash[:notice] ="Boom! you updated this correctly! Go Have Beers!"
        redirect_to lists_path
      else
        render :edit
      end
    end

    def destroy
      @list = List.find(params[:id])
      @list.destroy
      flash[:notice] = "List was DESTROYED"
      redirect_to lists_path
    end
  end

  private
  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
      if @task.save
        flash[:notice] = "Yay! You saved a task all by yourself! Go get Beers!"
        redirect_to list_path(@task.list)
      else
        render :new
      end
    end

    def edit
      @list = List.find(params[:list_id])
      @task = Task.find(params[:id])
    end

    def update
      @list = List.find(params[:list_id])
      @task = Task.find(params[:id])
        if @task.update(task_params)
          flash[:notice] = "Yay--you changed this all by yourself like a big person! Go get Beers!"
          redirect_to list_path(@task.list)
        else
          render :edit
        end
      end

      def destroy
        @task = Task.find(params[:id])
        @task.destroy
        flash[:notice] = "Task DESTROYED. Must.Get.BEERS!"
        redirect_to list_path(@task.list)
      end

      private
      def task_params
        params.require(:task).permit(:description)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please get off your ass and fix what you have broken: </h3>
  <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>  

</body>
</html>

app/views/lists/_form.html.erb
<%= render 'layouts/errors', :object => @list  %>

<%= form_for @list do |f| %>
<div class='form-control'>
  <%= f.label :name  %>
  <%= f.text_field :name %>

</div>
  <p><%= f.submit :class => "btn btn-block" %></p>
<% end %>

app/views/lists/edit.html.erb
<% content_for(:title, "Edit List | To Do") %>

<h1> Edit List </h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<% content_for(:title, "Home |To Do") %>

<h1> Lists </h1>
<div class='form-group'
  <ul>
      <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>
</div>
  <%= link_to "Add List", new_list_path, :class => "btn btn-primary" %>

app/views/lists/new.html.erb
<% content_for(:title, "New List | To Do") %>
<h1>New List</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>

  <% if @list.tasks.any? %>
    <h4> Here are the tasks for this list:</h4>

    <ul>
      <% @list.tasks.each do |task| %>
        <li>
          <%= task.description %> |
          <%= link_to "Edit", edit_list_task_path(@list, task), :class =>"btn btn-default" %> |
          <%= link_to "Delete", list_task_path(@list, task),
                        :data =>{:confirm => 'Are you sure?',
                                  :method =>'delete'},
                                  :class => "btn btn-danger" %>
        </li>
        <% end %>
      <ul>
    <% else %>
        <p> There are no tasks, yet--no beers for you until you get your work done!"</p>
    <% end %>


<p><%= link_to "Add a Task", new_list_task_path(@list), :class => "btn btn-default" %></p>
<p><%= link_to "Delete List", list_path(@list),
              :data => {:confirm => "Are you sure?",
              :method => "delete"},
              :class => "btn btn-danger" %></p>

<p><%= link_to "Return to Lists", lists_path, :class => "btn btn-default" %></p>

app/views/tasks/_form.html.erb
<%= render 'layouts/errors', :object => @task %>

<%= form_for [@list, @task] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <p><%= f.submit :class => "btn btn-primary" %></p>
<% end %>  

app/views/tasks/edit.html.erb
<% content_for(:title, 'Edit Task | To Do') %>

<h1>Edit Task</h1>

<%= render 'form' %>

app/views/tasks/new.html.erb
<% content_for(:title, "New  Task | To Do") %>

<h1>New Task for <%= @task.list.name %></h1>

<%= render 'form' %>